version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - TZ=America/Sao_Paulo

  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    volumes:
      - ./supabase/migrations:/migrations
    env_file: .env
    environment:
      - TZ=America/Sao_Paulo
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING:-postgresql://postgres:postgres@localhost:5432/postgres}
    restart: on-failure