FROM node:20-alpine

WORKDIR /app
RUN apk add --no-cache postgresql-client

COPY package*.json ./
RUN npm ci
COPY scripts/migration.js ./scripts/
COPY supabase/migrations /migrations

CMD ["node", "scripts/migration.js"]