version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - '3000:3000'
    env_file:
      - .env

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    env_file:
      - .env
